# Generated by Django 5.2.11 on 2026-02-23 23:55

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contacted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('lead_score', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tech_stack', models.JSONField(blank=True, default=dict)),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-lead_score'],
                'indexes': [models.Index(fields=['-lead_score', 'contacted', 'is_active'], name='sales_insti_lead_sc_bcec8e_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tech_stack'], name='tech_stack_gin_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('lead_score__gte', 0), ('lead_score__lte', 100)), name='lead_score_range_0_to_100')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sales.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message_sent', models.TextField()),
                ('opened_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('SENT', 'Enviado'), ('OPENED', 'Abierto'), ('REPLIED', 'Respondido')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.contact')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.institution')),
            ],
        ),
    ]
