# Generated by Django 5.2.11 on 2026-02-24 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-lead_score'], 'verbose_name': 'Institución Educativa', 'verbose_name_plural': 'Instituciones Educativas'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Física'),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(db_index=True, default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='institution',
            name='discovery_source',
            field=models.CharField(choices=[('osm', 'OpenStreetMap'), ('gov_data', 'Directorio Gubernamental'), ('serp', 'Buscador (Web Scraping)'), ('manual', 'Ingreso Manual / CRM')], default='manual', max_length=20, verbose_name='Origen del Dato'),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('kindergarten', 'Jardín Infantil / Preescolar'), ('school', 'Colegio (Básica/Media)'), ('university', 'Universidad / Educación Superior'), ('institute', 'Instituto Técnico / Tecnológico'), ('other', 'Otro')], default='school', max_length=20, verbose_name='Nivel Educativo'),
        ),
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Principal'),
        ),
        migrations.AddField(
            model_name='institution',
            name='state_region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Estado / Región'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(db_index=True, default='Desconocida', max_length=100, verbose_name='Ciudad / Municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='contacted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Contactado'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Principal'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo en CRM'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_private',
            field=models.BooleanField(db_index=True, default=True, help_text='Las privadas suelen tener mayor presupuesto para software.', verbose_name='Es Privada'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='last_scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Escaneo Forense'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='lead_score',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de Venta (0-100)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='student_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estudiantes Estimados'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict, verbose_name='Inteligencia Estructurada (JSON)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.contact'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='message_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('SENT', 'Enviado'), ('OPENED', 'Abierto'), ('REPLIED', 'Respondido'), ('MEETING', 'Reunión Agendada'), ('CLOSED', 'Cerrado')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['country', 'state_region', 'city'], name='sales_insti_country_7b5d82_idx'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('name', 'city', 'country'), name='unique_institution_per_city_country'),
        ),
    ]
