# Generated by Django 5.2.11 on 2026-02-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_institution_options_alter_interaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCenter',
            fields=[
            ],
            options={
                'verbose_name': '🚀 Sovereign Command Center',
                'verbose_name_plural': '🚀 Sovereign Command Center',
                'permissions': [('can_execute_osm_radar', 'Security: Can launch OSM Satellite Discovery'), ('can_execute_serp_resolver', 'Security: Can launch SERP URL Resolver'), ('can_execute_ghost_sniper', 'Security: Can launch the Ghost Sniper Engine'), ('view_executive_dashboard', 'Analytics: Can view C-Level Pipeline Metrics')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.institution',),
        ),
    ]
