# Generated by Django 5.2.11 on 2026-02-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_commandcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepForensicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_classification', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Clasificación IA')),
                ('executive_summary', models.TextField(blank=True, null=True, verbose_name='Resumen Ejecutivo')),
                ('sales_playbook', models.JSONField(blank=True, default=list, verbose_name='Recomendaciones Tácticas (Lista)')),
                ('predictive_copy', models.TextField(blank=True, null=True, verbose_name='Draft de Cold Email')),
                ('estimated_budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Presupuesto Estimado')),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil Forense IA',
                'verbose_name_plural': 'Perfiles Forenses IA',
            },
        ),
        migrations.CreateModel(
            name='TechProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_lms', models.BooleanField(db_index=True, default=False)),
                ('lms_provider', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Proveedor LMS (Ej: Moodle)')),
                ('is_wordpress', models.BooleanField(default=False, verbose_name='Usa WordPress')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Tiene Google Analytics/Tag Manager')),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil Tecnológico',
                'verbose_name_plural': 'Perfiles Tecnológicos',
            },
        ),
        migrations.RemoveIndex(
            model_name='institution',
            name='tech_stack_gin_idx',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='tech_stack',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_private',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Es Privada'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='last_scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Escaneo'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forensic_profile', to='sales.institution'),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_profile', to='sales.institution'),
        ),
    ]
