# Generated by Django 5.2.11 on 2026-02-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_deepforensicprofile_techprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRadarWorkspace',
            fields=[
            ],
            options={
                'verbose_name': '3. 🛰️ Geospatial Radar',
                'verbose_name_plural': '3. 🛰️ Geospatial Radar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.institution',),
        ),
        migrations.CreateModel(
            name='GlobalPipeline',
            fields=[
            ],
            options={
                'verbose_name': '1. 🌐 Global Database',
                'verbose_name_plural': '1. 🌐 Global Database',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.institution',),
        ),
        migrations.CreateModel(
            name='SniperConsole',
            fields=[
            ],
            options={
                'verbose_name': '2. 🎯 Sniper Console',
                'verbose_name_plural': '2. 🎯 Sniper Console',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.institution',),
        ),
        migrations.AddField(
            model_name='institution',
            name='mission_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID de Misión'),
        ),
    ]
