# Generated by Django 5.2.11 on 2026-02-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_georadarworkspace_globalpipeline_sniperconsole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contacted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Fase 1 Completada'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='replied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Prospecto Respondió'),
        ),
    ]
