# Generated by Django 5.2.11 on 2026-02-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_institution_contacted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interacción B2B', 'verbose_name_plural': 'Interacciones B2B'},
        ),
        migrations.AddField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email Cold Outreach'), ('LINKEDIN', 'LinkedIn InMail/Mensaje'), ('CALL', 'Llamada Telefónica')], db_index=True, default='EMAIL', max_length=20, verbose_name='Canal de Outreach'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='clicked_count',
            field=models.IntegerField(default=0, verbose_name='Clics en Enlaces (Deep Links)'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='message_received',
            field=models.TextField(blank=True, null=True, verbose_name='Payload Recibido (Respuesta Cruda)'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='telemetry_data',
            field=models.JSONField(blank=True, default=dict, help_text='Esquema libre para almacenar el intent detectado, latencias y metadata del protocolo.', verbose_name='Telemetría Forense (Headers, IPs, User-Agent, Sentimiento NLP)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='sales.contact'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='institution',
            field=models.ForeignKey(help_text='Nodo Institucional Padre', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.institution'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reunión (Si aplica)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='message_sent',
            field=models.TextField(blank=True, null=True, verbose_name='Payload Enviado (Copy Generado)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='opened_count',
            field=models.IntegerField(default=0, verbose_name='Aperturas (Tracking Pixel)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='replied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Conversión Lograda (Respondió)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo (Pendiente)'), ('QUEUED', 'En Cola (Worker)'), ('SENT', 'Enviado (Entregado al MTA)'), ('OPENED', 'Abierto (Tracking Pixel)'), ('REPLIED', 'Respondido (Inbound Interceptado)'), ('MEETING', 'Reunión Agendada (Conversión Exitoso)'), ('BOUNCED', 'Rebotado (Hard/Soft Bounce)'), ('CLOSED', 'Cerrado (Sin Interés/Perdido)')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto del Mensaje'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['institution', 'status'], name='sales_inter_institu_215ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['status', 'replied'], name='sales_inter_status_f97602_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['created_at', 'channel'], name='sales_inter_created_0b2662_idx'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'MEETING'), _negated=True), ('meeting_date__isnull', False), _connector='OR'), name='interaction_meeting_requires_date'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REPLIED'), _negated=True), ('replied', True), _connector='OR'), name='interaction_replied_status_sync'),
        ),
    ]
