# Generated by Django 5.2.11 on 2026-02-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_interaction_options_interaction_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email Cold Outreach'), ('WHATSAPP', 'WhatsApp Business API'), ('LINKEDIN', 'LinkedIn InMail/Mensaje'), ('CALL', 'Llamada Telefónica')], db_index=True, default='EMAIL', max_length=20, verbose_name='Canal de Outreach'),
        ),
    ]
