# Generated by Django 5.2.11 on 2026-02-28 02:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_interaction_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-lead_score', '-updated_at'], 'verbose_name': 'Institución Educativa', 'verbose_name_plural': 'Instituciones Educativas'},
        ),
        migrations.RemoveConstraint(
            model_name='interaction',
            name='interaction_meeting_requires_date',
        ),
        migrations.RemoveConstraint(
            model_name='interaction',
            name='interaction_replied_status_sync',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='sales_inter_created_0b2662_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_valid_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data Profunda Cruda (DOM Completo JSON)'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_cambridge_cert',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Certificación Cambridge'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_ib_cert',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Certificación IB (Bachillerato Internacional)'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='is_bilingual',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Es Bilingüe'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='is_trilingual',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Es Trilingüe'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='languages_detected',
            field=models.JSONField(blank=True, default=list, verbose_name="Lista de Idiomas (Ej: ['Inglés', 'Francés'])"),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='pedagogical_emphasis',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Énfasis (Ej: Montessori, STEAM)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='processing_status',
            field=models.CharField(choices=[('RAW', 'Crudo (Solo Mapa/Radar)'), ('LOCKED', 'Bloqueado (Sniper Extrayendo)'), ('ENRICHED', 'Enriquecido (Listo para Ventas)'), ('DISCARDED', 'Descartado (Falso Positivo/Caído)')], db_index=True, default='RAW', max_length=20, verbose_name='Estado en Pipeline'),
        ),
        migrations.AddField(
            model_name='institution',
            name='url_trust_score',
            field=models.FloatField(db_comment='Filtro matemático para descartar Falsos Positivos de URLs antes del Scrape.', default=0.0, help_text='Heurística de Levenshtein (Qué tan real es la URL)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='interaction',
            name='ai_sentiment',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sentimiento (Positivo/Negativo/Objeción)'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='next_action_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Próxima Acción (IA Follow-up)'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID de Hilo (Contexto IA)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC).', db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC).'),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='ai_classification',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC).', db_index=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='estimated_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='executive_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forensic_profile', related_query_name='forensic_profile', to='sales.institution'),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='predictive_copy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='sales_playbook',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC).'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contacted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(db_index=True, default='Colombia', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC).', db_index=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='discovery_source',
            field=models.CharField(choices=[('osm', 'OpenStreetMap (GeoRadar)'), ('gov_data', 'Directorio Gubernamental'), ('serp', 'SERP Engine (Web Scraping)'), ('manual', 'CRM Inbound / Manual'), ('Ghost_V20', 'Ghost Sniper V20 (Autonomous)')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Principal (Sanitizado)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('kindergarten', 'Jardín Infantil / Preescolar'), ('school', 'Colegio (Básica/Media)'), ('university', 'Universidad / Educación Superior'), ('institute', 'Instituto Técnico / Tecnológico'), ('other', 'Otro')], db_index=True, default='school', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_private',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='last_scored_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='lead_score',
            field=models.IntegerField(db_comment='Termómetro de Venta Predictivo (0-100).', db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='mission_id',
            field=models.UUIDField(blank=True, db_comment='Agrupador lógico para campañas Celery (Swarm ID).', db_index=True, null=True, verbose_name='ID de Misión/Batch'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{8,15}$', message='Formato E.164 o local válido requerido.')], verbose_name='Línea Directa / PBX'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='state_region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='student_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC).'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Sitio Web Oficial'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('LINKEDIN', 'LinkedIn'), ('CALL', 'Llamada')], db_index=True, default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='clicked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC).', db_index=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.institution'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='message_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='message_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='opened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='replied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo (Pendiente)'), ('QUEUED', 'En Cola (Worker)'), ('SENT', 'Enviado (Entregado)'), ('OPENED', 'Abierto (Pixel Tracking)'), ('REPLIED', 'Respondido (Inbound)'), ('MEETING', 'Reunión Agendada (Success)'), ('BOUNCED', 'Rebotado (Fallo de Red/Email)'), ('CLOSED', 'Cerrado (Perdido/Sin Interés)')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='telemetry_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC).'),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC).', db_index=True),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='has_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_profile', related_query_name='tech_profile', to='sales.institution'),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='is_wordpress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='lms_provider',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC).'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['institution', 'role'], name='sales_conta_institu_7a97d1_idx'),
        ),
        migrations.AddIndex(
            model_name='deepforensicprofile',
            index=models.Index(fields=['is_bilingual', 'is_trilingual'], name='sales_deepf_is_bili_54e30a_idx'),
        ),
        migrations.AddIndex(
            model_name='deepforensicprofile',
            index=models.Index(fields=['has_ib_cert', 'has_cambridge_cert'], name='sales_deepf_has_ib__016f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['processing_status', 'city'], name='sales_insti_process_0c93ac_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(condition=models.Q(('is_active', True), ('website__isnull', False), ('processing_status', 'RAW')), fields=['processing_status', 'website'], name='idx_sniper_queue'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['thread_id', 'created_at'], name='sales_inter_thread__ef55b2_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['next_action_date'], name='sales_inter_next_ac_ecd754_idx'),
        ),
    ]
