# Generated by Django 5.2.11 on 2026-03-27 13:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='discovery_source',
            field=models.CharField(choices=[('osm', 'OpenStreetMap (GeoRadar)'), ('gov_data', 'Directorio Gubernamental'), ('serp', 'SERP Engine (Web Scraping)'), ('manual', 'CRM Inbound / Manual'), ('Ghost_V23', 'Ghost Sniper V23 (Autonomous)')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, help_text='Soporta formato Ghost Sniper (Ej: W:3001234567 T:6011234567)', max_length=120, null=True, verbose_name='Omni-Canal (WA/TEL)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='NeuralForensicReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUIDv4 para blindar el acceso a los reportes de inteligencia (Anti-Scraping ID).', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En Espera / Encolado'), ('PROCESSING', 'Procesando (Inferencia IA)'), ('COMPLETED', 'Completado Exitosamente'), ('FAILED', 'Fallo de Inferencia / Timeout'), ('PARTIAL', 'Completado con Alucinaciones/Incompleto')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado del Análisis')),
                ('comprehensive_report', models.TextField(blank=True, help_text='El output en crudo (Markdown/Texto) generado por el LLM diseñado para el equipo de ventas.', null=True, verbose_name='Reporte Estratégico B2B (Human Readable)')),
                ('structured_intel', models.JSONField(blank=True, help_text="Diccionario JSON extraído por la IA (Ej: {'has_stem': true, 'is_ib': false, 'icfes_score': 'A+'}). Permite consultas complejas en BD.", null=True, verbose_name='Inteligencia Estructurada (Machine Readable)')),
                ('ai_model_version', models.CharField(choices=[('deepseek-chat', 'DeepSeek V3 / Coder'), ('gpt-4o-mini', 'OpenAI GPT-4 Omni Mini'), ('gpt-4o', 'OpenAI GPT-4 Omni'), ('claude-3-5-sonnet', 'Anthropic Claude 3.5 Sonnet'), ('llama-3-8b', 'Local LLaMA 3 (Fallback)'), ('unknown', 'Desconocido / Legacy')], default='unknown', help_text='Identifica el motor cognitivo que produjo este resultado para auditoría de calidad.', max_length=50, verbose_name='Versión del Modelo LLM')),
                ('raw_corpus_size', models.IntegerField(default=0, help_text='Cantidad de caracteres del HTML limpiado enviados al LLM en el prompt.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tamaño del Corpus Web (Caracteres)')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, help_text='Para cálculo de costos de Ingesta (FinOps).', verbose_name='Tokens de Entrada (Prompt)')),
                ('completion_tokens', models.PositiveIntegerField(default=0, help_text='Para cálculo de costos de Generación (FinOps).', verbose_name='Tokens de Salida (Completion)')),
                ('processing_latency_ms', models.PositiveIntegerField(default=0, help_text='Milisegundos que tardó el proveedor de IA en responder la petición HTTP.', verbose_name='Latencia de Inferencia (ms)')),
                ('error_traceback', models.TextField(blank=True, help_text='Almacena el stacktrace si la llamada a la IA o el parseo JSON falla.', null=True, verbose_name='Traza de Error (Debug)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización general')),
                ('analyzed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Momento exacto del Análisis IA')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neural_report', to='sales.institution')),
            ],
            options={
                'verbose_name': 'Reporte Neural de IA',
                'verbose_name_plural': 'Reportes Neurales de IA',
                'db_table': 'sales_neural_forensic_report',
                'ordering': ['-analyzed_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'ai_model_version'], name='sales_neura_status_5796d9_idx'), models.Index(fields=['-analyzed_at', 'status'], name='sales_neura_analyze_e6763b_idx')],
            },
        ),
    ]
