# Generated by Django 5.2.11 on 2026-03-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_contact_created_at_alter_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepforensicprofile',
            name='ai_comprehensive_report',
            field=models.TextField(blank=True, help_text='Reporte Markdown generado por el LLM (DeepSeek/OpenAI) con análisis cualitativo B2B.', null=True, verbose_name='Reporte Estratégico IA'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='ai_structured_data',
            field=models.JSONField(blank=True, help_text='Diccionario JSON estricto forzado por Prompt Engineering para consultas avanzadas (O(1)).', null=True, verbose_name='Data Estructurada (JSON)'),
        ),
        migrations.DeleteModel(
            name='NeuralForensicReport',
        ),
    ]
