# Generated by Django 5.2.11 on 2026-03-31 13:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_deepforensicprofile_ai_comprehensive_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandcenter',
            options={'permissions': [('can_execute_osm_radar', 'Security: Can launch OSM Satellite Discovery'), ('can_execute_serp_resolver', 'Security: Can launch SERP URL Resolver'), ('can_execute_ghost_sniper', 'Security: Can launch the Ghost Sniper Engine'), ('view_executive_dashboard', 'Analytics: Can view C-Level Pipeline Metrics'), ('can_generate_cosmic_reports', 'AI: Can generate Cosmic AI Reports'), ('view_cosmic_intelligence', 'AI: Can view Cosmic Intelligence Reports')], 'verbose_name': '🚀 Sovereign Command Center (Omega)', 'verbose_name_plural': '🚀 Sovereign Command Center (Omega)'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto (Omega)', 'verbose_name_plural': 'Contactos (Omega)'},
        ),
        migrations.AlterModelOptions(
            name='deepforensicprofile',
            options={'verbose_name': '🌌 Perfil Forense IA (Cosmic)', 'verbose_name_plural': '🌌 Perfiles Forenses IA (Cosmic)'},
        ),
        migrations.AlterModelOptions(
            name='georadarworkspace',
            options={'verbose_name': '3. 🛰️ Geospatial Radar (Omega)', 'verbose_name_plural': '3. 🛰️ Geospatial Radar (Omega)'},
        ),
        migrations.AlterModelOptions(
            name='globalpipeline',
            options={'verbose_name': '1. 🌐 Global Database (Cosmic)', 'verbose_name_plural': '1. 🌐 Global Database (Cosmic)'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-lead_score', '-updated_at', '-confidence_score'], 'verbose_name': '🌌 Institución Educativa (Cosmic)', 'verbose_name_plural': '🌌 Instituciones Educativas (Cosmic)'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at'], 'verbose_name': '🌌 Interacción B2B (Cosmic)', 'verbose_name_plural': '🌌 Interacciones B2B (Cosmic)'},
        ),
        migrations.AlterModelOptions(
            name='sniperconsole',
            options={'verbose_name': '2. 🎯 Sniper Console (Omega)', 'verbose_name_plural': '2. 🎯 Sniper Console (Omega)'},
        ),
        migrations.AlterModelOptions(
            name='techprofile',
            options={'verbose_name': 'Perfil Tecnológico (Omega)', 'verbose_name_plural': 'Perfiles Tecnológicos (Omega)'},
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_inst_role',
            old_name='sales_conta_institu_7a97d1_idx',
        ),
        migrations.RenameIndex(
            model_name='deepforensicprofile',
            new_name='idx_bilingual_trilingual',
            old_name='sales_deepf_is_bili_54e30a_idx',
        ),
        migrations.RenameIndex(
            model_name='deepforensicprofile',
            new_name='idx_ib_cambridge',
            old_name='sales_deepf_has_ib__016f6b_idx',
        ),
        migrations.RenameIndex(
            model_name='institution',
            new_name='idx_processing_city',
            old_name='sales_insti_process_0c93ac_idx',
        ),
        migrations.RenameIndex(
            model_name='institution',
            new_name='idx_score_contacted_active',
            old_name='sales_insti_lead_sc_bcec8e_idx',
        ),
        migrations.RenameIndex(
            model_name='institution',
            new_name='idx_geo_location',
            old_name='sales_insti_country_7b5d82_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='idx_inst_status',
            old_name='sales_inter_institu_215ac7_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='idx_status_replied',
            old_name='sales_inter_status_f97602_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='idx_thread_created',
            old_name='sales_inter_thread__ef55b2_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='idx_next_action',
            old_name='sales_inter_next_ac_ecd754_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='Fecha de expiración para purga automática de datos obsoletos.', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_decision_maker',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_technical_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone', 'Teléfono'), ('linkedin', 'LinkedIn')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='academic_emphasis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Énfasis Académico'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='arts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='cambridge_center_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='cambridge_exams',
            field=models.JSONField(blank=True, default=list, verbose_name='Exámenes Cambridge ofrecidos'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='campus_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='clubs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='corporate_agreements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='efqm',
            field=models.BooleanField(default=False, verbose_name='EFQM'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='estimated_revenue_potential',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Potencial de Ingreso Estimado'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='Fecha de expiración para purga automática de datos obsoletos.', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='great_place_to_study',
            field=models.BooleanField(default=False, verbose_name='Great Place to Study'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_ai_initiatives',
            field=models.BooleanField(default=False, verbose_name='Iniciativas de IA'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_dining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_ielts_cert',
            field=models.BooleanField(default=False, verbose_name='Certificación IELTS'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_oxford_cert',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Certificación Oxford'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_programming',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Programación'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_robotics',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Programa de Robótica'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_stem',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Programa STEM'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_toefl_cert',
            field=models.BooleanField(default=False, verbose_name='Certificación TOEFL'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='has_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='ib_programs',
            field=models.JSONField(blank=True, default=list, verbose_name='Programas IB (PYP/MYP/DP)'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='ib_since',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='ideal_contact_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol de Contacto Ideal'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='international_agreements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='is_multilingual',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Es Multilingüe'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='iso_14001',
            field=models.BooleanField(default=False, verbose_name='ISO 14001'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='iso_9001',
            field=models.BooleanField(default=False, verbose_name='ISO 9001'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='language_levels',
            field=models.JSONField(blank=True, default=dict, verbose_name='Niveles por idioma'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='opportunities',
            field=models.JSONField(blank=True, default=list, verbose_name='Oportunidades Comerciales'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='other_certifications',
            field=models.JSONField(blank=True, default=list, verbose_name='Otras certificaciones'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='pain_points',
            field=models.JSONField(blank=True, default=list, verbose_name='Pain Points Detectados'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='pedagogical_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Pedagógico'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='programming_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalles de Programación'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='recommended_approach',
            field=models.TextField(blank=True, null=True, verbose_name='Enfoque de Venta Recomendado'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='robotics_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalles de Robótica'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='sales_priority',
            field=models.CharField(choices=[('High', 'Alta'), ('Medium', 'Media'), ('Low', 'Baja')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='sales_triggers',
            field=models.JSONField(blank=True, default=list, verbose_name='Sales Triggers'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='sports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='sports_facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='stem_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalles de STEM'),
        ),
        migrations.AddField(
            model_name='deepforensicprofile',
            name='university_agreements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institution',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Confianza del análisis (0-1). Mayor a 0.85 es confiable.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='institution',
            name='cryptographic_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Hash SHA-256 de nombre+ciudad+país para deduplicación global.', max_length=64, null=True, unique=True, verbose_name='Fingerprint Criptográfico'),
        ),
        migrations.AddField(
            model_name='institution',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='Fecha de expiración para purga automática de datos obsoletos.', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='extraction_completeness',
            field=models.FloatField(default=0.0, help_text='Completitud de la extracción de datos (0-1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='institution',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='icfes_category',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='icfes_ranking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='icfes_score',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='search_hash',
            field=models.CharField(blank=True, db_comment='Anti-duplicación por lote: mismo hash = misma sesión de búsqueda.', db_index=True, help_text='Hash SHA-256 de la sesión de búsqueda. Cambia cada 5 minutos para evitar duplicados en el mismo lote.', max_length=64, null=True, verbose_name='Hash de Búsqueda Cuántico'),
        ),
        migrations.AddField(
            model_name='institution',
            name='social_media',
            field=models.JSONField(blank=True, db_comment='Extracción completa de perfiles sociales.', default=dict, help_text='Diccionario con URLs de redes sociales (facebook, instagram, linkedin, etc.)', verbose_name='Redes Sociales'),
        ),
        migrations.AddField(
            model_name='institution',
            name='teacher_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='whatsapp_numbers',
            field=models.JSONField(blank=True, db_comment='Extracción masiva de números WhatsApp del sitio web.', default=list, help_text='Lista de números de WhatsApp detectados.', verbose_name='Números de WhatsApp'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='Fecha de expiración para purga automática de datos obsoletos.', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='follow_up_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='last_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='sentiment_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='analytics_providers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='cms_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='detected_lms_list',
            field=models.JSONField(blank=True, default=list, help_text='Lista de todos los LMS detectados'),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='Fecha de expiración para purga automática de datos obsoletos.', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='frontend_framework',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='has_cloudflare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='has_custom_cms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='has_ecommerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='has_modern_frontend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='has_schema_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='has_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='hosting_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='lms_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='lms_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='payment_providers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='seo_framework',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='wordpress_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC). Usado para TTL y auditoría forense.', db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC). Usado para caché y scoring.'),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='ai_comprehensive_report',
            field=models.TextField(blank=True, help_text='Reporte Markdown generado por el LLM (DeepSeek/OpenAI) con análisis cualitativo B2B completo.', null=True, verbose_name='🌌 Reporte Estratégico IA (Cosmic Edition)'),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='ai_structured_data',
            field=models.JSONField(blank=True, help_text='Diccionario JSON estricto forzado por Prompt Engineering para consultas avanzadas O(1).', null=True, verbose_name='📊 Data Estructurada (JSON) - Cosmic Intelligence'),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC). Usado para TTL y auditoría forense.', db_index=True),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='HTML procesado y datos extraídos para análisis.', verbose_name='Data Profunda Cruda (DOM Completo JSON)'),
        ),
        migrations.AlterField(
            model_name='deepforensicprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC). Usado para caché y scoring.'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC). Usado para TTL y auditoría forense.', db_index=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='discovery_source',
            field=models.CharField(choices=[('osm', '🛰️ OpenStreetMap (GeoRadar)'), ('gov_data', '🏛️ Directorio Gubernamental'), ('serp', '🔍 SERP Engine (Web Scraping)'), ('manual', '✍️ CRM Inbound / Manual'), ('Ghost_Omega_V99', '👻 Ghost Sniper Omega V99 (Autonomous)'), ('cosmic_ai', '🌌 Cosmic AI Discovery')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email principal validado y sanitizado.', max_length=254, null=True, verbose_name='Email Principal (Sanitizado)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.UUIDField(db_comment='UUIDv4 criptográfico para blindar el acceso y prevenir enumeración.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('kindergarten', '🏫 Jardín Infantil / Preescolar'), ('school', '📚 Colegio (Básica/Media)'), ('university', '🎓 Universidad / Educación Superior'), ('institute', '⚙️ Instituto Técnico / Tecnológico'), ('other', '📖 Otro')], db_index=True, default='school', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='lead_score',
            field=models.IntegerField(db_comment='Termómetro de Venta Predictivo (0-100). Actualizado por ML semanalmente.', db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='mission_id',
            field=models.UUIDField(blank=True, db_comment='Agrupador lógico para campañas Celery (Swarm ID). Permite trazabilidad end-to-end.', db_index=True, null=True, verbose_name='ID de Misión/Batch'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre oficial de la institución educativa.', max_length=255, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, db_comment='Formato unificado: W: para WhatsApp, T: para teléfono fijo.', help_text='Soporta formato Ghost Sniper (Ej: W:3001234567 T:6011234567)', max_length=120, null=True, verbose_name='Omni-Canal (WA/TEL)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='processing_status',
            field=models.CharField(choices=[('RAW', '🌍 Crudo (Solo Mapa/Radar)'), ('LOCKED', '🎯 Bloqueado (Sniper Extrayendo)'), ('ENRICHED', '✨ Enriquecido (Listo para Ventas)'), ('DISCARDED', '🗑️ Descartado (Falso Positivo/Caído)'), ('AI_PROCESSING', '🧠 Procesando con IA Cósmica'), ('COSMIC', '🌌 Reporte Cósmico Generado')], db_index=True, default='RAW', max_length=20, verbose_name='Estado en Pipeline'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC). Usado para caché y scoring.'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, db_comment='URL canónica oficial. Única para evitar duplicados.', max_length=255, null=True, unique=True, verbose_name='Sitio Web Oficial'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('EMAIL', '📧 Email'), ('WHATSAPP', '💬 WhatsApp'), ('LINKEDIN', '🔗 LinkedIn'), ('CALL', '📞 Llamada')], db_index=True, default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC). Usado para TTL y auditoría forense.', db_index=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('NEW', '📝 Nuevo (Pendiente)'), ('QUEUED', '⏳ En Cola (Worker)'), ('SENT', '📨 Enviado (Entregado)'), ('OPENED', '👁️ Abierto (Pixel Tracking)'), ('REPLIED', '💬 Respondido (Inbound)'), ('MEETING', '📅 Reunión Agendada (Success)'), ('BOUNCED', '⚠️ Rebotado (Fallo de Red/Email)'), ('CLOSED', '🔒 Cerrado (Perdido/Sin Interés)')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID que agrupa toda la conversación.', max_length=255, null=True, verbose_name='ID de Hilo (Contexto IA)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC). Usado para caché y scoring.'),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp inmutable de creación (UTC). Usado para TTL y auditoría forense.', db_index=True),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp dinámico de última mutación (UTC). Usado para caché y scoring.'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_decision_maker', 'contact_score'], name='idx_dm_score'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='idx_contact_email'),
        ),
        migrations.AddIndex(
            model_name='deepforensicprofile',
            index=models.Index(fields=['has_robotics', 'has_stem', 'has_programming'], name='idx_tech_programs'),
        ),
        migrations.AddIndex(
            model_name='deepforensicprofile',
            index=models.Index(fields=['sales_priority', 'ai_confidence_score'], name='idx_sales_priority'),
        ),
        migrations.AddIndex(
            model_name='deepforensicprofile',
            index=models.Index(fields=['pedagogical_emphasis'], name='idx_pedagogical_emphasis'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['search_hash', 'city', 'name'], name='idx_search_hash_city_name'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['cryptographic_fingerprint'], name='idx_crypto_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['lead_score', 'confidence_score'], name='idx_score_confidence'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['icfes_score', 'icfes_category'], name='idx_icfes_performance'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['institution_type', 'is_private'], name='idx_type_private'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['city', 'lead_score'], name='idx_city_score'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['channel', 'status'], name='idx_channel_status'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['contact', 'created_at'], name='idx_contact_created'),
        ),
        migrations.AddIndex(
            model_name='techprofile',
            index=models.Index(fields=['lms_provider', 'has_lms'], name='sales_techp_lms_pro_b72713_idx'),
        ),
        migrations.AddIndex(
            model_name='techprofile',
            index=models.Index(fields=['is_wordpress', 'has_analytics'], name='sales_techp_is_word_d1a9f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), name='confidence_score_range'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.CheckConstraint(condition=models.Q(('extraction_completeness__gte', 0), ('extraction_completeness__lte', 1)), name='completeness_range'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(condition=models.Q(('cryptographic_fingerprint__isnull', False)), fields=('cryptographic_fingerprint',), name='unique_crypto_fingerprint'),
        ),
    ]
