# Generated by Django 5.2.11 on 2026-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_commandcenter_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='direction',
            field=models.CharField(choices=[('OUT', '📤 Saliente (Nosotros/IA)'), ('IN', '📥 Entrante (Cliente)')], db_index=True, default='OUT', max_length=10),
        ),
        migrations.AddField(
            model_name='interaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Firma SHA-256 del contenido para evitar procesar el mismo webhook/email dos veces.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_ai_generated',
            field=models.BooleanField(default=True, help_text='True si lo escribió el modelo. False si fue intervención manual o respuesta del cliente.', verbose_name='Generado por IA'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['institution', 'direction', 'created_at'], name='idx_inst_dir_created'),
        ),
    ]
