# Generated by Django 5.2.11 on 2026-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_interaction_direction_interaction_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-contact_score', '-created_at'], 'verbose_name': 'Contacto (Omega)', 'verbose_name_plural': 'Contactos (Omega)'},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_inst_role',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_con_em_unq',
            old_name='idx_contact_email',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_con_dm_pr',
            old_name='idx_dm_score',
        ),
        migrations.AddField(
            model_name='contact',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_ai_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_ai_thought_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='pause_automations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('LEAD', '🔥 Lead Nuevo'), ('RESEARCHING', '🔍 En Investigación AI'), ('EMAIL_SENT', '📧 Email Enviado'), ('WHATSAPP_SENT', '📱 WhatsApp Enviado'), ('REPLIED', '💬 Respondió'), ('ENGAGED', '🎯 Interesado'), ('PAUSED', '⛔ Pausado'), ('REJECTED', '❌ No Interesado'), ('CONVERTED', '🏆 Cliente')], db_index=True, default='LEAD', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status', 'pause_automations'], name='idx_con_st_pau'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['institution', 'status'], name='idx_con_inst_st'),
        ),
    ]
