# Generated by Django 5.2.11 on 2026-04-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_contact_options_remove_contact_idx_inst_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Inicio'), ('EMAIL_SENT', 'Correo Enviado (Paso 1)'), ('WHATSAPP_SENT', 'WhatsApp Enviado (Paso 2)'), ('SMS_SENT', 'SMS Enviado (Paso 3)'), ('REPLIED', 'El cliente respondió (Cacería Pausada)'), ('MEETING_BOOKED', 'Reunión Agendada (ÉXITO)'), ('BOUNCED', 'Error de envío')], default='PENDING', max_length=20)),
                ('ai_thought_process_memory', models.TextField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_sequences', to='sales.contact')),
            ],
            options={
                'verbose_name': 'Secuencia de Prospección',
                'verbose_name_plural': 'Secuencias de Prospección',
            },
        ),
    ]
